"""Command Zero Python SDK.

Quick start::

    from cmdzero import CommandZero

    cz = CommandZero(api_key="c0...", organization_id="<uuid>")
    print(cz.health.check())
    for inv in cz.investigations.list(filter="status eq 'pending-review'"):
        print(inv.id, inv.severity, inv.title)
"""
from __future__ import annotations

from .client import CommandZero
from .enums import (
    PATCHABLE_INVESTIGATION_STATUSES,
    AlertEntryAction,
    AttributionType,
    BusinessContextStatus,
    ConfidenceLevel,
    CreateInvestigationAction,
    HealthStatus,
    Impact,
    InvestigationStatus,
    InvestigationType,
    PostbackMethod,
    RemediationStatus,
    Role,
    Sensitivity,
    Severity,
)
from .exceptions import (
    BadRequestError,
    CommandZeroError,
    ConflictError,
    ForbiddenError,
    NotFoundError,
    RateLimitError,
    ServerError,
    TransportError,
    UnauthorizedError,
    UnprocessableEntityError,
)
from .models import (
    Application,
    Attribution,
    BusinessContextUpload,
    CatalogType,
    CatalogTypeField,
    CreateBusinessContextUploadRequest,
    CreateInvestigationRequest,
    CreateInvestigationResponse,
    CreateRemediationRequest,
    Error,
    HealthResponse,
    Investigation,
    InvestigationAlertEntry,
    InvestigationPostbackPayload,
    InvestigationSubject,
    InvestigationTemplate,
    ListApplicationsResponse,
    ListBusinessContextUploadsResponse,
    ListCatalogTypesResponse,
    ListInvestigationTemplatesResponse,
    ListInvestigationsResponse,
    ListOrganizationsResponse,
    ListRemediationTemplatesResponse,
    ListRemediationsResponse,
    ListUsersResponse,
    Observable,
    Organization,
    Postback,
    QueryRequest,
    Remediation,
    RemediationPostbackPayload,
    RemediationSubject,
    RemediationTemplate,
    ReplaceBusinessContextUploadRequest,
    TypeAnnotation,
    UpdateInvestigationRequest,
    User,
    UserReference,
)
from .pagination import PaginatedIterator
from .transport import DEFAULT_BASE_URL, HttpTransport

__version__ = "0.1.0"

__all__ = [
    # Top-level client
    "CommandZero",
    "HttpTransport",
    "DEFAULT_BASE_URL",
    "PaginatedIterator",
    "__version__",
    # Exceptions
    "CommandZeroError",
    "TransportError",
    "BadRequestError",
    "UnauthorizedError",
    "ForbiddenError",
    "NotFoundError",
    "ConflictError",
    "UnprocessableEntityError",
    "RateLimitError",
    "ServerError",
    # Enums
    "Severity",
    "Sensitivity",
    "ConfidenceLevel",
    "Impact",
    "InvestigationType",
    "InvestigationStatus",
    "RemediationStatus",
    "Role",
    "AlertEntryAction",
    "AttributionType",
    "BusinessContextStatus",
    "PostbackMethod",
    "HealthStatus",
    "CreateInvestigationAction",
    "PATCHABLE_INVESTIGATION_STATUSES",
    # Models
    "Attribution",
    "Error",
    "TypeAnnotation",
    "Postback",
    "Observable",
    "UserReference",
    "QueryRequest",
    "HealthResponse",
    "Organization",
    "ListOrganizationsResponse",
    "Application",
    "ListApplicationsResponse",
    "User",
    "ListUsersResponse",
    "CatalogType",
    "CatalogTypeField",
    "ListCatalogTypesResponse",
    "BusinessContextUpload",
    "CreateBusinessContextUploadRequest",
    "ReplaceBusinessContextUploadRequest",
    "ListBusinessContextUploadsResponse",
    "InvestigationTemplate",
    "ListInvestigationTemplatesResponse",
    "InvestigationSubject",
    "InvestigationAlertEntry",
    "CreateInvestigationRequest",
    "UpdateInvestigationRequest",
    "Investigation",
    "CreateInvestigationResponse",
    "ListInvestigationsResponse",
    "InvestigationPostbackPayload",
    "RemediationSubject",
    "RemediationTemplate",
    "ListRemediationTemplatesResponse",
    "CreateRemediationRequest",
    "Remediation",
    "ListRemediationsResponse",
    "RemediationPostbackPayload",
]
